# Generated by Django 2.2.12 on 2021-01-25 07:29

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sign',
            field=models.CharField(default=user.models.default_sign, max_length=50, verbose_name='个人签名'),
        ),
    ]
